version: '3.9'

services:
  api:
    container_name: api
    image: nuchal-api:v1.0.0
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  pgdata: